name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk wget
          pip install --upgrade pip
          pip install buildozer cython kivy

      - name: Install Android SDK (user-level)
        run: |
          mkdir -p ~/.android
          echo "count=0" > ~/.android/repositories.cfg
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
          unzip tools.zip -d latest
          rm tools.zip

          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platforms;android-35" "build-tools;36.1.0" "platform-tools"

      - name: Unzip project
        run: |
          unzip expedicao-heron1-main.zip -d app

      - name: Build APK with Buildozer
        run: |
          cd app
          export ANDROIDSDK=$HOME/android-sdk
          export PATH=$ANDROIDSDK/cmdline-tools/latest/bin:$PATH
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-expedicao
          path: app/bin/*.apk
